language: objective-c
compiler:
  - gcc
  - clang
env:
  - TEST_FOLDER=mono TEST_TARGET=check CI=1 V=1
  - TEST_FOLDER=mcs TEST_TARGET=compiler-tests
  - TEST_FOLDER=mcs/class/corlib TEST_TARGET="run-test" PROFILE=net_2_0
  - TEST_FOLDER=mcs/class TEST_TARGET="test run-test" PROFILE=net_3_5
  - TEST_FOLDER=mcs/class/corlib TEST_TARGET="test run-test" PROFILE=net_4_0
  - TEST_FOLDER=mcs/class/corlib TEST_TARGET="test run-test" PROFILE=net_4_5
  - TEST_FOLDER=mcs/class TEST_TARGET="test run-test" PROFILE=xbuild_12
before_install:
  - date
  - ./autogen.sh
install:
  - date
  - make get-monolite-latest
script:
  - date
  - make -j8 EXTERNAL_MCS=${PWD}/mcs/class/lib/monolite/gmcs.exe
  - date
  # why is "make install" needed for testing? (issues with path resolution?)
  - sudo make install
  - date
  - make -C $TEST_FOLDER $TEST_TARGET
  - date
