language: c
compiler:
  - gcc
  - clang
env:
  - TEST_FOLDER=mono TEST_TARGET=check CI=1 V=1
before_install:
  - cat /proc/cpuinfo
  - sudo apt-get update -qq
  - sudo apt-get install -qq gdb
  - ./autogen.sh
install:
  - make get-monolite-latest
script:
  - make -j8 EXTERNAL_MCS=${PWD}/mcs/class/lib/monolite/gmcs.exe
  - sudo make install
  - make -C $TEST_FOLDER $TEST_TARGET
  - cd mono/tests
  - (echo "handle all noprint" ; echo "handle SIGABRT stop" ; echo "run" ; sleep 60 ; echo "thread apply all bt") | gdb --args mono bug-18026.exe
